-- ============================================================
-- SPRINT 5: USE CASES SEED
-- 10 Use Cases × 7 Sprachen (DE, EN, FR, ES, IT, NL, PL)
-- Datum: 2026-06-14 | ZERO RISK – nur INSERT, keine Updates
-- Compliance: "Research Use Only" Framing überall
-- ============================================================

-- HINWEIS: Vor Ausführung sicherstellen dass Migration 0013 bereits angewendet wurde.
-- Ausführung: psql $DATABASE_URL < sprint5_use_cases_seed.sql

-- ============================================================
-- 1. USE CASES (Basis-Tabelle)
-- ============================================================

INSERT INTO use_cases (slug, icon, sort_order, is_active, visible) VALUES
  ('fat-loss',            '🔥', 1, 1, 1),
  ('longevity',           '⏳', 2, 1, 1),
  ('beauty',              '✨', 3, 1, 1),
  ('performance',         '⚡', 4, 1, 1),
  ('sleep',               '🌙', 5, 1, 1),
  ('brain',               '🧠', 6, 1, 1),
  ('metabolic-research',  '🔬', 7, 1, 1),
  ('mitochondrial-support','⚙️', 8, 1, 1),
  ('cosmetic-peptides',   '💎', 9, 1, 1),
  ('recovery',            '🔄', 10, 1, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 2. USE CASE TRANSLATIONS
-- ============================================================

-- ---- FAT-LOSS ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='fat-loss'), 'de',
   'Fettabbau & Metabolismus',
   'Fettabbau',
   'Evidenzbasierte Research Compounds für metabolische Optimierung.',
   'Peptide wie Retatrutide und Tirzepatide werden in der Forschung intensiv auf ihre Wirkung auf den Fettstoffwechsel, GLP-1-Signalwege und metabolische Adaptation untersucht. 369 Research bietet EU-grade Compounds für Forschungszwecke.',
   'Fettabbau Peptide – Research Compounds | 369 Research',
   'Research Compounds für metabolische Forschung: Retatrutide, Tirzepatide & GLP-1 Agonisten. EU-grade Qualität. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='fat-loss'), 'en',
   'Fat Loss & Metabolic Research',
   'Fat Loss',
   'Evidence-based research compounds for metabolic optimization.',
   'Peptides such as Retatrutide and Tirzepatide are extensively studied for their effects on fat metabolism, GLP-1 signaling pathways, and metabolic adaptation. 369 Research provides EU-grade compounds for research purposes.',
   'Fat Loss Peptides – Research Compounds | 369 Research',
   'Research compounds for metabolic research: Retatrutide, Tirzepatide & GLP-1 agonists. EU-grade quality. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='fat-loss'), 'fr',
   'Perte de Graisse & Recherche Métabolique',
   'Perte de Graisse',
   'Composés de recherche basés sur des preuves pour l''optimisation métabolique.',
   'Des peptides comme le Rétatrutide et le Tirzépatide sont intensément étudiés pour leurs effets sur le métabolisme des graisses et les voies de signalisation GLP-1.',
   'Peptides Perte de Graisse – Composés de Recherche | 369 Research',
   'Composés de recherche pour la recherche métabolique: Rétatrutide, Tirzépatide & agonistes GLP-1. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='fat-loss'), 'es',
   'Pérdida de Grasa & Investigación Metabólica',
   'Pérdida de Grasa',
   'Compuestos de investigación basados en evidencia para la optimización metabólica.',
   'Péptidos como Retatrutida y Tirzepatida se estudian intensamente por sus efectos en el metabolismo de las grasas y las vías de señalización GLP-1.',
   'Péptidos Pérdida de Grasa – Compuestos de Investigación | 369 Research',
   'Compuestos de investigación para investigación metabólica: Retatrutida, Tirzepatida & agonistas GLP-1. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='fat-loss'), 'it',
   'Perdita di Grasso & Ricerca Metabolica',
   'Perdita di Grasso',
   'Composti di ricerca basati su prove per l''ottimizzazione metabolica.',
   'Peptidi come Retatrutide e Tirzepatide sono studiati intensamente per i loro effetti sul metabolismo dei grassi e le vie di segnalazione GLP-1.',
   'Peptidi Perdita di Grasso – Composti di Ricerca | 369 Research',
   'Composti di ricerca per la ricerca metabolica: Retatrutide, Tirzepatide & agonisti GLP-1. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='fat-loss'), 'nl',
   'Vetverlies & Metabolisch Onderzoek',
   'Vetverlies',
   'Op bewijs gebaseerde onderzoeksverbindingen voor metabolische optimalisatie.',
   'Peptiden zoals Retatrutide en Tirzepatide worden intensief bestudeerd op hun effecten op het vetmetabolisme en GLP-1 signaleringsroutes.',
   'Vetverlies Peptiden – Onderzoeksverbindingen | 369 Research',
   'Onderzoeksverbindingen voor metabolisch onderzoek: Retatrutide, Tirzepatide & GLP-1 agonisten. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='fat-loss'), 'pl',
   'Utrata Tłuszczu & Badania Metaboliczne',
   'Utrata Tłuszczu',
   'Związki badawcze oparte na dowodach do optymalizacji metabolicznej.',
   'Peptydy takie jak Retatrutyd i Tirzepatyd są intensywnie badane pod kątem wpływu na metabolizm tłuszczów i szlaki sygnalizacyjne GLP-1.',
   'Peptydy Utrata Tłuszczu – Związki Badawcze | 369 Research',
   'Związki badawcze do badań metabolicznych: Retatrutyd, Tirzepatyd & agoniści GLP-1. Jakość EU. Tylko do badań.');

-- ---- LONGEVITY ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='longevity'), 'de',
   'Longevity & Zellalterung',
   'Longevity',
   'Mitochondriale und zelluläre Forschungsverbindungen für Langlebigkeitsforschung.',
   'SS-31, MOTS-C und Epithalon werden in der Alternsforschung auf ihre Wirkung auf mitochondriale Funktion, Telomerlänge und zelluläre Seneszenz untersucht. Research Use Only.',
   'Longevity Peptide – Anti-Aging Research | 369 Research',
   'Research Compounds für Longevity-Forschung: SS-31, MOTS-C, Epithalon. Mitochondriale Unterstützung. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='longevity'), 'en',
   'Longevity & Cellular Aging Research',
   'Longevity',
   'Mitochondrial and cellular research compounds for longevity research.',
   'SS-31, MOTS-C, and Epithalon are studied in aging research for their effects on mitochondrial function, telomere length, and cellular senescence. Research Use Only.',
   'Longevity Peptides – Anti-Aging Research | 369 Research',
   'Research compounds for longevity research: SS-31, MOTS-C, Epithalon. Mitochondrial support. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='longevity'), 'fr',
   'Longévité & Vieillissement Cellulaire',
   'Longévité',
   'Composés de recherche mitochondriaux pour la recherche sur la longévité.',
   'SS-31, MOTS-C et Épithalon sont étudiés pour leurs effets sur la fonction mitochondriale et la sénescence cellulaire.',
   'Peptides Longévité – Recherche Anti-Âge | 369 Research',
   'Composés de recherche pour la longévité: SS-31, MOTS-C, Épithalon. Soutien mitochondrial. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='longevity'), 'es',
   'Longevidad & Envejecimiento Celular',
   'Longevidad',
   'Compuestos de investigación mitocondriales para la investigación de la longevidad.',
   'SS-31, MOTS-C y Epithalon se estudian por sus efectos sobre la función mitocondrial y la senescencia celular.',
   'Péptidos Longevidad – Investigación Anti-Envejecimiento | 369 Research',
   'Compuestos de investigación para longevidad: SS-31, MOTS-C, Epithalon. Soporte mitocondrial. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='longevity'), 'it',
   'Longevità & Invecchiamento Cellulare',
   'Longevità',
   'Composti di ricerca mitocondriali per la ricerca sulla longevità.',
   'SS-31, MOTS-C ed Epithalon sono studiati per i loro effetti sulla funzione mitocondriale e la senescenza cellulare.',
   'Peptidi Longevità – Ricerca Anti-Invecchiamento | 369 Research',
   'Composti di ricerca per la longevità: SS-31, MOTS-C, Epithalon. Supporto mitocondriale. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='longevity'), 'nl',
   'Levensduur & Cellulaire Veroudering',
   'Levensduur',
   'Mitochondriale onderzoeksverbindingen voor levensduuronderzoek.',
   'SS-31, MOTS-C en Epithalon worden bestudeerd op hun effecten op mitochondriale functie en cellulaire senescentie.',
   'Levensduur Peptiden – Anti-Veroudering Onderzoek | 369 Research',
   'Onderzoeksverbindingen voor levensduuronderzoek: SS-31, MOTS-C, Epithalon. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='longevity'), 'pl',
   'Długowieczność & Starzenie Komórkowe',
   'Długowieczność',
   'Mitochondrialne związki badawcze do badań nad długowiecznością.',
   'SS-31, MOTS-C i Epithalon są badane pod kątem wpływu na funkcję mitochondrialną i starzenie komórkowe.',
   'Peptydy Długowieczność – Badania Anti-Aging | 369 Research',
   'Związki badawcze do badań nad długowiecznością: SS-31, MOTS-C, Epithalon. Jakość EU. Tylko do badań.');

-- ---- BEAUTY ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='beauty'), 'de',
   'Beauty & Hautforschung',
   'Beauty',
   'Kosmetische Peptide für Kollagensynthese und Hautstrukturforschung.',
   'GHK-Cu, SNAP-8 und Matrixyl werden in der Dermatologie-Forschung auf ihre Wirkung auf Kollagensynthese, Hautelastizität und Wundheilung untersucht. Research Use Only.',
   'Beauty Peptide – Hautforschung Research Compounds | 369 Research',
   'Kosmetische Research Compounds: GHK-Cu, SNAP-8, Matrixyl. Kollagensynthese-Forschung. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='beauty'), 'en',
   'Beauty & Skin Research',
   'Beauty',
   'Cosmetic peptides for collagen synthesis and skin structure research.',
   'GHK-Cu, SNAP-8, and Matrixyl are studied in dermatology research for their effects on collagen synthesis, skin elasticity, and wound healing. Research Use Only.',
   'Beauty Peptides – Skin Research Compounds | 369 Research',
   'Cosmetic research compounds: GHK-Cu, SNAP-8, Matrixyl. Collagen synthesis research. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='beauty'), 'fr',
   'Beauté & Recherche Cutanée',
   'Beauté',
   'Peptides cosmétiques pour la recherche sur la synthèse du collagène.',
   'GHK-Cu, SNAP-8 et Matrixyl sont étudiés pour leurs effets sur la synthèse du collagène et l''élasticité cutanée.',
   'Peptides Beauté – Composés de Recherche Cutanée | 369 Research',
   'Composés de recherche cosmétiques: GHK-Cu, SNAP-8, Matrixyl. Recherche collagène. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='beauty'), 'es',
   'Belleza & Investigación Cutánea',
   'Belleza',
   'Péptidos cosméticos para la investigación de síntesis de colágeno.',
   'GHK-Cu, SNAP-8 y Matrixyl se estudian por sus efectos sobre la síntesis de colágeno y la elasticidad cutánea.',
   'Péptidos Belleza – Compuestos de Investigación Cutánea | 369 Research',
   'Compuestos de investigación cosméticos: GHK-Cu, SNAP-8, Matrixyl. Investigación colágeno. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='beauty'), 'it',
   'Bellezza & Ricerca Cutanea',
   'Bellezza',
   'Peptidi cosmetici per la ricerca sulla sintesi del collagene.',
   'GHK-Cu, SNAP-8 e Matrixyl sono studiati per i loro effetti sulla sintesi del collagene e l''elasticità cutanea.',
   'Peptidi Bellezza – Composti di Ricerca Cutanea | 369 Research',
   'Composti di ricerca cosmetici: GHK-Cu, SNAP-8, Matrixyl. Ricerca collagene. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='beauty'), 'nl',
   'Schoonheid & Huidonderzoek',
   'Schoonheid',
   'Cosmetische peptiden voor collageen synthese en huidstructuuronderzoek.',
   'GHK-Cu, SNAP-8 en Matrixyl worden bestudeerd op hun effecten op collageensynthese en huidelasticiteit.',
   'Schoonheid Peptiden – Huidonderzoek Verbindingen | 369 Research',
   'Cosmetische onderzoeksverbindingen: GHK-Cu, SNAP-8, Matrixyl. Collageen onderzoek. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='beauty'), 'pl',
   'Uroda & Badania Skóry',
   'Uroda',
   'Kosmetyczne peptydy do badań syntezy kolagenu i struktury skóry.',
   'GHK-Cu, SNAP-8 i Matrixyl są badane pod kątem wpływu na syntezę kolagenu i elastyczność skóry.',
   'Peptydy Uroda – Związki Badawcze Skóry | 369 Research',
   'Kosmetyczne związki badawcze: GHK-Cu, SNAP-8, Matrixyl. Badania kolagenu. Jakość EU. Tylko do badań.');

-- ---- PERFORMANCE ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='performance'), 'de',
   'Performance & GH-Achse',
   'Performance',
   'GH-Sekretagoga und Muskelschutz-Peptide für Leistungsforschung.',
   'Ipamorelin, CJC-1295 und Tesamorelin werden in der Sportmedizin-Forschung auf ihre Wirkung auf die GH-Achse, Muskelmasse und Körperzusammensetzung untersucht. Research Use Only.',
   'Performance Peptide – GH-Achse Research | 369 Research',
   'Research Compounds für Leistungsforschung: Ipamorelin, CJC-1295, Tesamorelin. GH-Achse. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='performance'), 'en',
   'Performance & GH Axis Research',
   'Performance',
   'GH secretagogues and muscle protection peptides for performance research.',
   'Ipamorelin, CJC-1295, and Tesamorelin are studied in sports medicine research for their effects on the GH axis, muscle mass, and body composition. Research Use Only.',
   'Performance Peptides – GH Axis Research | 369 Research',
   'Research compounds for performance research: Ipamorelin, CJC-1295, Tesamorelin. GH axis. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='performance'), 'fr',
   'Performance & Axe GH',
   'Performance',
   'Sécrétagogues GH et peptides de protection musculaire pour la recherche.',
   'Ipamorelin, CJC-1295 et Tésamorelin sont étudiés pour leurs effets sur l''axe GH et la composition corporelle.',
   'Peptides Performance – Recherche Axe GH | 369 Research',
   'Composés de recherche pour la performance: Ipamorelin, CJC-1295, Tésamorelin. Axe GH. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='performance'), 'es',
   'Rendimiento & Eje GH',
   'Rendimiento',
   'Secretagogos GH y péptidos de protección muscular para investigación.',
   'Ipamorelin, CJC-1295 y Tesamorelin se estudian por sus efectos sobre el eje GH y la composición corporal.',
   'Péptidos Rendimiento – Investigación Eje GH | 369 Research',
   'Compuestos de investigación para rendimiento: Ipamorelin, CJC-1295, Tesamorelin. Eje GH. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='performance'), 'it',
   'Prestazione & Asse GH',
   'Prestazione',
   'Secretagoghi GH e peptidi di protezione muscolare per la ricerca.',
   'Ipamorelin, CJC-1295 e Tesamorelin sono studiati per i loro effetti sull''asse GH e la composizione corporea.',
   'Peptidi Prestazione – Ricerca Asse GH | 369 Research',
   'Composti di ricerca per la prestazione: Ipamorelin, CJC-1295, Tesamorelin. Asse GH. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='performance'), 'nl',
   'Prestatie & GH-As Onderzoek',
   'Prestatie',
   'GH secretagogen en spierprotectie peptiden voor prestatieonderzoek.',
   'Ipamorelin, CJC-1295 en Tesamorelin worden bestudeerd op hun effecten op de GH-as en lichaamssamenstelling.',
   'Prestatie Peptiden – GH-As Onderzoek | 369 Research',
   'Onderzoeksverbindingen voor prestatieonderzoek: Ipamorelin, CJC-1295, Tesamorelin. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='performance'), 'pl',
   'Wydajność & Oś GH',
   'Wydajność',
   'Sekretagogi GH i peptydy ochrony mięśni do badań wydajności.',
   'Ipamorelin, CJC-1295 i Tesamorelin są badane pod kątem wpływu na oś GH i skład ciała.',
   'Peptydy Wydajność – Badania Osi GH | 369 Research',
   'Związki badawcze do badań wydajności: Ipamorelin, CJC-1295, Tesamorelin. Jakość EU. Tylko do badań.');

-- ---- SLEEP ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='sleep'), 'de',
   'Schlaf & Erholung',
   'Schlaf',
   'Neuropeptide für Schlafqualität und zirkadianen Rhythmus-Forschung.',
   'Selank, Semax und DSIP werden in der Neurologie-Forschung auf ihre Wirkung auf Schlafarchitektur, Stressreduktion und zirkadianen Rhythmus untersucht. Research Use Only.',
   'Schlaf Peptide – Schlafforschung Research Compounds | 369 Research',
   'Research Compounds für Schlafforschung: Selank, Semax, DSIP. Zirkadianer Rhythmus. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='sleep'), 'en',
   'Sleep & Recovery Research',
   'Sleep',
   'Neuropeptides for sleep quality and circadian rhythm research.',
   'Selank, Semax, and DSIP are studied in neurology research for their effects on sleep architecture, stress reduction, and circadian rhythm. Research Use Only.',
   'Sleep Peptides – Sleep Research Compounds | 369 Research',
   'Research compounds for sleep research: Selank, Semax, DSIP. Circadian rhythm. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='sleep'), 'fr',
   'Sommeil & Récupération',
   'Sommeil',
   'Neuropeptides pour la recherche sur la qualité du sommeil.',
   'Selank, Semax et DSIP sont étudiés pour leurs effets sur l''architecture du sommeil et le rythme circadien.',
   'Peptides Sommeil – Composés de Recherche | 369 Research',
   'Composés de recherche pour le sommeil: Selank, Semax, DSIP. Rythme circadien. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='sleep'), 'es',
   'Sueño & Recuperación',
   'Sueño',
   'Neuropéptidos para la investigación de la calidad del sueño.',
   'Selank, Semax y DSIP se estudian por sus efectos sobre la arquitectura del sueño y el ritmo circadiano.',
   'Péptidos Sueño – Compuestos de Investigación | 369 Research',
   'Compuestos de investigación para el sueño: Selank, Semax, DSIP. Ritmo circadiano. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='sleep'), 'it',
   'Sonno & Recupero',
   'Sonno',
   'Neuropeptidi per la ricerca sulla qualità del sonno.',
   'Selank, Semax e DSIP sono studiati per i loro effetti sull''architettura del sonno e il ritmo circadiano.',
   'Peptidi Sonno – Composti di Ricerca | 369 Research',
   'Composti di ricerca per il sonno: Selank, Semax, DSIP. Ritmo circadiano. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='sleep'), 'nl',
   'Slaap & Herstel Onderzoek',
   'Slaap',
   'Neuropeptiden voor slaapkwaliteit en circadiaans ritme onderzoek.',
   'Selank, Semax en DSIP worden bestudeerd op hun effecten op slaaparchitectuur en circadiaans ritme.',
   'Slaap Peptiden – Onderzoeksverbindingen | 369 Research',
   'Onderzoeksverbindingen voor slaaponderzoek: Selank, Semax, DSIP. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='sleep'), 'pl',
   'Sen & Regeneracja',
   'Sen',
   'Neuropeptydy do badań jakości snu i rytmu dobowego.',
   'Selank, Semax i DSIP są badane pod kątem wpływu na architekturę snu i rytm dobowy.',
   'Peptydy Sen – Związki Badawcze | 369 Research',
   'Związki badawcze do badań snu: Selank, Semax, DSIP. Rytm dobowy. Jakość EU. Tylko do badań.');

-- ---- BRAIN ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='brain'), 'de',
   'Kognition & Neuroprotektion',
   'Gehirn',
   'Nootrope Peptide für kognitive Funktion und Neuroprotektions-Forschung.',
   'Semax, Selank und Dihexa werden in der Neurowissenschafts-Forschung auf ihre Wirkung auf BDNF, kognitive Funktion und neuronale Plastizität untersucht. Research Use Only.',
   'Nootrope Peptide – Kognitions-Forschung | 369 Research',
   'Research Compounds für Kognitionsforschung: Semax, Selank, Dihexa. BDNF, Neuroprotektion. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='brain'), 'en',
   'Cognition & Neuroprotection Research',
   'Brain',
   'Nootropic peptides for cognitive function and neuroprotection research.',
   'Semax, Selank, and Dihexa are studied in neuroscience research for their effects on BDNF, cognitive function, and neural plasticity. Research Use Only.',
   'Nootropic Peptides – Cognition Research | 369 Research',
   'Research compounds for cognition research: Semax, Selank, Dihexa. BDNF, neuroprotection. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='brain'), 'fr',
   'Cognition & Neuroprotection',
   'Cerveau',
   'Peptides nootropiques pour la recherche sur la fonction cognitive.',
   'Semax, Selank et Dihexa sont étudiés pour leurs effets sur le BDNF et la plasticité neuronale.',
   'Peptides Nootropiques – Recherche Cognitive | 369 Research',
   'Composés de recherche pour la cognition: Semax, Selank, Dihexa. BDNF. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='brain'), 'es',
   'Cognición & Neuroprotección',
   'Cerebro',
   'Péptidos nootrópicos para la investigación de la función cognitiva.',
   'Semax, Selank y Dihexa se estudian por sus efectos sobre el BDNF y la plasticidad neuronal.',
   'Péptidos Nootrópicos – Investigación Cognitiva | 369 Research',
   'Compuestos de investigación para cognición: Semax, Selank, Dihexa. BDNF. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='brain'), 'it',
   'Cognizione & Neuroprotezione',
   'Cervello',
   'Peptidi nootropici per la ricerca sulla funzione cognitiva.',
   'Semax, Selank e Dihexa sono studiati per i loro effetti sul BDNF e la plasticità neuronale.',
   'Peptidi Nootropici – Ricerca Cognitiva | 369 Research',
   'Composti di ricerca per la cognizione: Semax, Selank, Dihexa. BDNF. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='brain'), 'nl',
   'Cognitie & Neuroprotectie Onderzoek',
   'Hersenen',
   'Nootropische peptiden voor cognitieve functie en neuroprotectie onderzoek.',
   'Semax, Selank en Dihexa worden bestudeerd op hun effecten op BDNF en neuronale plasticiteit.',
   'Nootropische Peptiden – Cognitie Onderzoek | 369 Research',
   'Onderzoeksverbindingen voor cognitie: Semax, Selank, Dihexa. BDNF. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='brain'), 'pl',
   'Kognicja & Neuroprotekcja',
   'Mózg',
   'Nootropowe peptydy do badań funkcji poznawczych i neuroprotekcji.',
   'Semax, Selank i Dihexa są badane pod kątem wpływu na BDNF i plastyczność neuronalną.',
   'Nootropowe Peptydy – Badania Kognicji | 369 Research',
   'Związki badawcze do badań kognicji: Semax, Selank, Dihexa. BDNF. Jakość EU. Tylko do badań.');

-- ---- METABOLIC-RESEARCH ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='metabolic-research'), 'de',
   'Metabolische Forschung & Insulinsensitivität',
   'Metabolismus',
   'AMPK-Aktivatoren und Insulinsensitizer für Stoffwechselforschung.',
   'Verbindungen wie AICAR und Metformin-Analoga werden in der metabolischen Forschung auf ihre Wirkung auf AMPK-Aktivierung, Insulinsensitivität und Glukosestoffwechsel untersucht. Research Use Only.',
   'Metabolische Forschung – AMPK Research Compounds | 369 Research',
   'Research Compounds für Metabolismus-Forschung: AMPK-Aktivatoren, Insulinsensitizer. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='metabolic-research'), 'en',
   'Metabolic Research & Insulin Sensitivity',
   'Metabolism',
   'AMPK activators and insulin sensitizers for metabolic research.',
   'Compounds such as AICAR are studied in metabolic research for their effects on AMPK activation, insulin sensitivity, and glucose metabolism. Research Use Only.',
   'Metabolic Research – AMPK Research Compounds | 369 Research',
   'Research compounds for metabolic research: AMPK activators, insulin sensitizers. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='metabolic-research'), 'fr',
   'Recherche Métabolique & Sensibilité à l''Insuline',
   'Métabolisme',
   'Activateurs AMPK et sensibilisateurs à l''insuline pour la recherche métabolique.',
   'Des composés comme AICAR sont étudiés pour leurs effets sur l''activation AMPK et la sensibilité à l''insuline.',
   'Recherche Métabolique – Composés AMPK | 369 Research',
   'Composés de recherche métabolique: activateurs AMPK, sensibilisateurs insuline. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='metabolic-research'), 'es',
   'Investigación Metabólica & Sensibilidad a la Insulina',
   'Metabolismo',
   'Activadores AMPK y sensibilizadores de insulina para investigación metabólica.',
   'Compuestos como AICAR se estudian por sus efectos sobre la activación AMPK y la sensibilidad a la insulina.',
   'Investigación Metabólica – Compuestos AMPK | 369 Research',
   'Compuestos de investigación metabólica: activadores AMPK, sensibilizadores insulina. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='metabolic-research'), 'it',
   'Ricerca Metabolica & Sensibilità all''Insulina',
   'Metabolismo',
   'Attivatori AMPK e sensibilizzatori dell''insulina per la ricerca metabolica.',
   'Composti come AICAR sono studiati per i loro effetti sull''attivazione AMPK e la sensibilità all''insulina.',
   'Ricerca Metabolica – Composti AMPK | 369 Research',
   'Composti di ricerca metabolica: attivatori AMPK, sensibilizzatori insulina. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='metabolic-research'), 'nl',
   'Metabolisch Onderzoek & Insulinegevoeligheid',
   'Metabolisme',
   'AMPK activatoren en insuline sensibilisatoren voor metabolisch onderzoek.',
   'Verbindingen zoals AICAR worden bestudeerd op hun effecten op AMPK activering en insulinegevoeligheid.',
   'Metabolisch Onderzoek – AMPK Verbindingen | 369 Research',
   'Onderzoeksverbindingen voor metabolisme: AMPK activatoren, insuline sensibilisatoren. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='metabolic-research'), 'pl',
   'Badania Metaboliczne & Wrażliwość na Insulinę',
   'Metabolizm',
   'Aktywatory AMPK i sensybilizatory insuliny do badań metabolicznych.',
   'Związki takie jak AICAR są badane pod kątem wpływu na aktywację AMPK i wrażliwość na insulinę.',
   'Badania Metaboliczne – Związki AMPK | 369 Research',
   'Związki badawcze do metabolizmu: aktywatory AMPK, sensybilizatory insuliny. Jakość EU. Tylko do badań.');

-- ---- MITOCHONDRIAL-SUPPORT ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='mitochondrial-support'), 'de',
   'Mitochondriale Unterstützung & Zellenergie',
   'Mitochondrien',
   'SS-31 und MOTS-C für mitochondriale Funktion und Zellenergie-Forschung.',
   'SS-31 (Elamipretide) und MOTS-C werden in der Mitochondrien-Forschung auf ihre Wirkung auf ATP-Produktion, oxidativen Stress und mitochondriale Biogenese untersucht. Research Use Only.',
   'Mitochondriale Peptide – Zellenergie Research | 369 Research',
   'Research Compounds für Mitochondrien-Forschung: SS-31, MOTS-C. ATP-Produktion, oxidativer Stress. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='mitochondrial-support'), 'en',
   'Mitochondrial Support & Cellular Energy',
   'Mitochondria',
   'SS-31 and MOTS-C for mitochondrial function and cellular energy research.',
   'SS-31 (Elamipretide) and MOTS-C are studied in mitochondrial research for their effects on ATP production, oxidative stress, and mitochondrial biogenesis. Research Use Only.',
   'Mitochondrial Peptides – Cellular Energy Research | 369 Research',
   'Research compounds for mitochondrial research: SS-31, MOTS-C. ATP production, oxidative stress. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='mitochondrial-support'), 'fr',
   'Soutien Mitochondrial & Énergie Cellulaire',
   'Mitochondries',
   'SS-31 et MOTS-C pour la recherche sur la fonction mitochondriale.',
   'SS-31 et MOTS-C sont étudiés pour leurs effets sur la production d''ATP et le stress oxydatif.',
   'Peptides Mitochondriaux – Énergie Cellulaire | 369 Research',
   'Composés de recherche mitochondriaux: SS-31, MOTS-C. Production ATP. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='mitochondrial-support'), 'es',
   'Soporte Mitocondrial & Energía Celular',
   'Mitocondrias',
   'SS-31 y MOTS-C para la investigación de la función mitocondrial.',
   'SS-31 y MOTS-C se estudian por sus efectos sobre la producción de ATP y el estrés oxidativo.',
   'Péptidos Mitocondriales – Energía Celular | 369 Research',
   'Compuestos de investigación mitocondriales: SS-31, MOTS-C. Producción ATP. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='mitochondrial-support'), 'it',
   'Supporto Mitocondriale & Energia Cellulare',
   'Mitocondri',
   'SS-31 e MOTS-C per la ricerca sulla funzione mitocondriale.',
   'SS-31 e MOTS-C sono studiati per i loro effetti sulla produzione di ATP e lo stress ossidativo.',
   'Peptidi Mitocondriali – Energia Cellulare | 369 Research',
   'Composti di ricerca mitocondriali: SS-31, MOTS-C. Produzione ATP. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='mitochondrial-support'), 'nl',
   'Mitochondriale Ondersteuning & Celenergie',
   'Mitochondriën',
   'SS-31 en MOTS-C voor mitochondriale functie en celenergie onderzoek.',
   'SS-31 en MOTS-C worden bestudeerd op hun effecten op ATP-productie en oxidatieve stress.',
   'Mitochondriale Peptiden – Celenergie Onderzoek | 369 Research',
   'Mitochondriale onderzoeksverbindingen: SS-31, MOTS-C. ATP productie. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='mitochondrial-support'), 'pl',
   'Wsparcie Mitochondrialne & Energia Komórkowa',
   'Mitochondria',
   'SS-31 i MOTS-C do badań funkcji mitochondrialnej i energii komórkowej.',
   'SS-31 i MOTS-C są badane pod kątem wpływu na produkcję ATP i stres oksydacyjny.',
   'Mitochondrialne Peptydy – Energia Komórkowa | 369 Research',
   'Mitochondrialne związki badawcze: SS-31, MOTS-C. Produkcja ATP. Jakość EU. Tylko do badań.');

-- ---- COSMETIC-PEPTIDES ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='cosmetic-peptides'), 'de',
   'Kosmetische Peptide & Dermatologie',
   'Kosmetische Peptide',
   'Spezialisierte Peptide für Dermatologie- und Kosmetik-Forschung.',
   'GHK-Cu, SNAP-8 und weitere kosmetische Peptide werden in der Dermatologie-Forschung auf ihre Wirkung auf Hautalterung, Pigmentierung und Wundheilung untersucht. Research Use Only.',
   'Kosmetische Peptide – Dermatologie Research | 369 Research',
   'Kosmetische Research Compounds für Dermatologie: GHK-Cu, SNAP-8. Hautalterung, Pigmentierung. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='cosmetic-peptides'), 'en',
   'Cosmetic Peptides & Dermatology Research',
   'Cosmetic Peptides',
   'Specialized peptides for dermatology and cosmetic research.',
   'GHK-Cu, SNAP-8, and other cosmetic peptides are studied in dermatology research for their effects on skin aging, pigmentation, and wound healing. Research Use Only.',
   'Cosmetic Peptides – Dermatology Research | 369 Research',
   'Cosmetic research compounds for dermatology: GHK-Cu, SNAP-8. Skin aging, pigmentation. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='cosmetic-peptides'), 'fr',
   'Peptides Cosmétiques & Dermatologie',
   'Peptides Cosmétiques',
   'Peptides spécialisés pour la recherche en dermatologie et cosmétique.',
   'GHK-Cu, SNAP-8 et d''autres peptides cosmétiques sont étudiés pour leurs effets sur le vieillissement cutané et la cicatrisation.',
   'Peptides Cosmétiques – Recherche Dermatologique | 369 Research',
   'Composés cosmétiques pour la dermatologie: GHK-Cu, SNAP-8. Vieillissement cutané. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='cosmetic-peptides'), 'es',
   'Péptidos Cosméticos & Dermatología',
   'Péptidos Cosméticos',
   'Péptidos especializados para investigación en dermatología y cosmética.',
   'GHK-Cu, SNAP-8 y otros péptidos cosméticos se estudian por sus efectos sobre el envejecimiento cutáneo y la cicatrización.',
   'Péptidos Cosméticos – Investigación Dermatológica | 369 Research',
   'Compuestos cosméticos para dermatología: GHK-Cu, SNAP-8. Envejecimiento cutáneo. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='cosmetic-peptides'), 'it',
   'Peptidi Cosmetici & Dermatologia',
   'Peptidi Cosmetici',
   'Peptidi specializzati per la ricerca in dermatologia e cosmetica.',
   'GHK-Cu, SNAP-8 e altri peptidi cosmetici sono studiati per i loro effetti sull''invecchiamento cutaneo e la cicatrizzazione.',
   'Peptidi Cosmetici – Ricerca Dermatologica | 369 Research',
   'Composti cosmetici per la dermatologia: GHK-Cu, SNAP-8. Invecchiamento cutaneo. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='cosmetic-peptides'), 'nl',
   'Cosmetische Peptiden & Dermatologie',
   'Cosmetische Peptiden',
   'Gespecialiseerde peptiden voor dermatologie en cosmetisch onderzoek.',
   'GHK-Cu, SNAP-8 en andere cosmetische peptiden worden bestudeerd op hun effecten op huidveroudering en wondgenezing.',
   'Cosmetische Peptiden – Dermatologie Onderzoek | 369 Research',
   'Cosmetische onderzoeksverbindingen: GHK-Cu, SNAP-8. Huidveroudering. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='cosmetic-peptides'), 'pl',
   'Kosmetyczne Peptydy & Dermatologia',
   'Kosmetyczne Peptydy',
   'Specjalistyczne peptydy do badań dermatologicznych i kosmetycznych.',
   'GHK-Cu, SNAP-8 i inne kosmetyczne peptydy są badane pod kątem wpływu na starzenie skóry i gojenie ran.',
   'Kosmetyczne Peptydy – Badania Dermatologiczne | 369 Research',
   'Kosmetyczne związki badawcze: GHK-Cu, SNAP-8. Starzenie skóry. Jakość EU. Tylko do badań.');

-- ---- RECOVERY ----
INSERT INTO use_case_translations (use_case_id, lang, title, name, hero_text, description, seo_title, seo_description) VALUES
  ((SELECT id FROM use_cases WHERE slug='recovery'), 'de',
   'Regeneration & Gewebeheilung',
   'Regeneration',
   'BPC-157 und TB-500 für Gewebeheilung und Regenerations-Forschung.',
   'BPC-157 und TB-500 (Thymosin Beta-4) werden in der Regenerationsforschung auf ihre Wirkung auf Gewebeheilung, Angiogenese und entzündungshemmende Mechanismen untersucht. Research Use Only.',
   'Regeneration Peptide – Gewebeheilung Research | 369 Research',
   'Research Compounds für Regenerationsforschung: BPC-157, TB-500. Gewebeheilung, Angiogenese. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='recovery'), 'en',
   'Recovery & Tissue Healing Research',
   'Recovery',
   'BPC-157 and TB-500 for tissue healing and recovery research.',
   'BPC-157 and TB-500 (Thymosin Beta-4) are studied in regeneration research for their effects on tissue healing, angiogenesis, and anti-inflammatory mechanisms. Research Use Only.',
   'Recovery Peptides – Tissue Healing Research | 369 Research',
   'Research compounds for recovery research: BPC-157, TB-500. Tissue healing, angiogenesis. EU-grade. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='recovery'), 'fr',
   'Récupération & Guérison des Tissus',
   'Récupération',
   'BPC-157 et TB-500 pour la recherche sur la guérison des tissus.',
   'BPC-157 et TB-500 sont étudiés pour leurs effets sur la guérison des tissus et l''angiogenèse.',
   'Peptides Récupération – Guérison des Tissus | 369 Research',
   'Composés de recherche pour la récupération: BPC-157, TB-500. Guérison tissulaire. Qualité EU. Research Use Only.'),
  ((SELECT id FROM use_cases WHERE slug='recovery'), 'es',
   'Recuperación & Curación de Tejidos',
   'Recuperación',
   'BPC-157 y TB-500 para la investigación de curación de tejidos.',
   'BPC-157 y TB-500 se estudian por sus efectos sobre la curación de tejidos y la angiogénesis.',
   'Péptidos Recuperación – Curación de Tejidos | 369 Research',
   'Compuestos de investigación para recuperación: BPC-157, TB-500. Curación tisular. Calidad EU. Solo para investigación.'),
  ((SELECT id FROM use_cases WHERE slug='recovery'), 'it',
   'Recupero & Guarigione dei Tessuti',
   'Recupero',
   'BPC-157 e TB-500 per la ricerca sulla guarigione dei tessuti.',
   'BPC-157 e TB-500 sono studiati per i loro effetti sulla guarigione dei tessuti e l''angiogenesi.',
   'Peptidi Recupero – Guarigione dei Tessuti | 369 Research',
   'Composti di ricerca per il recupero: BPC-157, TB-500. Guarigione tissutale. Qualità EU. Solo per ricerca.'),
  ((SELECT id FROM use_cases WHERE slug='recovery'), 'nl',
   'Herstel & Weefselgenezing Onderzoek',
   'Herstel',
   'BPC-157 en TB-500 voor weefselgenezing en herstelonderzoek.',
   'BPC-157 en TB-500 worden bestudeerd op hun effecten op weefselgenezing en angiogenese.',
   'Herstel Peptiden – Weefselgenezing Onderzoek | 369 Research',
   'Onderzoeksverbindingen voor herstel: BPC-157, TB-500. Weefselgenezing. EU-kwaliteit. Alleen voor onderzoek.'),
  ((SELECT id FROM use_cases WHERE slug='recovery'), 'pl',
   'Regeneracja & Gojenie Tkanek',
   'Regeneracja',
   'BPC-157 i TB-500 do badań gojenia tkanek i regeneracji.',
   'BPC-157 i TB-500 są badane pod kątem wpływu na gojenie tkanek i angiogenezę.',
   'Peptydy Regeneracja – Gojenie Tkanek | 369 Research',
   'Związki badawcze do regeneracji: BPC-157, TB-500. Gojenie tkanek. Jakość EU. Tylko do badań.');
